# Global Config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager Configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load all rule files from /etc/prometheus/rules/
rule_files:
  - "/etc/prometheus/rules/*.yml"

sdsdsds
# Scrape Configurations
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "dynamic_jobs_test_new"
    file_sd_configs:
      - files:
          - "/etc/prometheus/jobs/*.yml"
