---
- name: Deploy Prometheus Configuration
  hosts: 192.168.0.104
  become: true
  remote_user: baborok

  tasks:
    - name: Install required dependencies
      apt:
        name: git
        state: present

    - name: Clone Prometheus Config Repository
      git:
        repo: "https://github.com/baborok/Prometheus-config.git"
        dest: "/home/baborok/prometheus-config"
        version: master
        force: yes

    - name: Ensure Prometheus configuration directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/prometheus
        - /etc/prometheus/rules
        - /etc/prometheus/jobs

    - name: Check if Prometheus configuration exists in repo
      stat:
        path: "/home/baborok/prometheus-config/prometheus.yml"
      register: prometheus_config

    - name: Copy Prometheus Configuration
      copy:
        src: "/home/baborok/prometheus-config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      when: prometheus_config.stat.exists
      notify: Restart Prometheus

    - name: Check if rules directory exists in repo
      stat:
        path: "/home/baborok/prometheus-config/rules/"
      register: rules_dir

    - name: Copy Alert Rules if directory exists
      synchronize:
        src: "/home/baborok/prometheus-config/rules/"
        dest: "/etc/prometheus/rules/"
        recursive: yes
      when: rules_dir.stat.exists
      notify: Restart Prometheus

    - name: Check if jobs directory exists in repo
      stat:
        path: "/home/baborok/prometheus-config/jobs/"
      register: jobs_dir

    - name: Copy Job Targets if directory exists
      synchronize:
        src: "/home/baborok/prometheus-config/jobs/"
        dest: "/etc/prometheus/jobs/"
        recursive: yes
      when: jobs_dir.stat.exists
      notify: Restart Prometheus

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
