---
- name: Deploy Prometheus Configuration
  hosts: target_machine
  become: true
  remote_user: baborok

  tasks:
    - name: Install required dependencies
      apt:
        name: git
        state: present

    - name: Clone or Update Prometheus Configuration Repository
      git:
        repo: "git@github.com:baborok/Prometheus-config.git"
        dest: "/home/baborok/prometheus-config"
        version: master
        update: yes
        force: yes  # Ensures local changes don't block updates

    - name: Ensure Prometheus configuration directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/prometheus
        - /etc/prometheus/rules
        - /etc/prometheus/jobs

    - name: Copy Prometheus Configuration
      copy:
        src: "/home/baborok/prometheus-config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

    - name: Copy Alert Rules
      copy:
        src: "/home/baborok/prometheus-config/rules/"
        dest: "/etc/prometheus/rules/"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

    - name: Copy Job Targets
      copy:
        src: "/home/baborok/prometheus-config/jobs/"
        dest: "/etc/prometheus/jobs/"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
