---
- name: Deploy Prometheus Configuration
  hosts: 192.168.0.104
  become: true
  remote_user: baborok

  tasks:
    - name: Install required dependencies
      apt:
        name: git
        state: present

    - name: Ensure Prometheus config repo is cloned on the target machine
      command: >
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null baborok@192.168.0.104
        'git clone --depth=1 git@github.com:baborok/Prometheus-config.git /home/baborok/prometheus-config || 
        (cd /home/baborok/prometheus-config && git pull)'
      args:
        creates: /home/baborok/prometheus-config

    - name: Ensure Prometheus configuration directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/prometheus
        - /etc/prometheus/rules
        - /etc/prometheus/jobs

    - name: Copy Prometheus Configuration
      copy:
        src: "/home/baborok/prometheus-config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

    - name: Copy Alert Rules
      copy:
        src: "/home/baborok/prometheus-config/rules/"
        dest: "/etc/prometheus/rules/"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

    - name: Copy Job Targets
      copy:
        src: "/home/baborok/prometheus-config/jobs/"
        dest: "/etc/prometheus/jobs/"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify: Restart Prometheus

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes

