---
- name: Deploy Prometheus Configuration
  hosts: 192.168.0.104
  become: true
  remote_user: baborok

  tasks:
    - name: Install required dependencies
      apt:
        name: git
        state: present
      become: true

    - name: Clone Prometheus Config Repository
      git:
        repo: "https://github.com/baborok/Prometheus-config.git"
        dest: "/home/baborok/prometheus-config"
        version: master
        force: yes

    - name: Ensure Prometheus configuration directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - /etc/prometheus/rules
        - /etc/prometheus/jobs

    - name: Copy Prometheus Configuration
      copy:
        src: "/home/baborok/prometheus-config/prometheus.yml"
        dest: "/etc/prometheus/prometheus.yml"
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      become: true

    - name: Copy Alert Rules
      synchronize:
        src: "/home/baborok/prometheus-config/rules/"
        dest: "/etc/prometheus/rules/"
        recursive: yes
      become: true

    - name: Copy Job Targets
      synchronize:
        src: "/home/baborok/prometheus-config/jobs/"
        dest: "/etc/prometheus/jobs/"
        recursive: yes
      become: true

    - name: Restart Prometheus Service
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
      become: true
