name: Deploy Prometheus Configuration

on:
  push:
    branches:
      - master
    paths:
      - "prometheus.yml"
      - "rules/**"
      - "jobs/**"

jobs:
  deploy:
    runs-on: prom-machine #vajno tut sam host ne self-host inache beda budet

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible git

      - name: Run Ansible Playbook
        run: |
          cd playbooks
          ansible-playbook -i localhost, -c local deploy_prometheus.yml
